pragma Singleton

// Emitting Lua, safely.
//
// Small on purpose. The generator writes a config file that Hyprland executes,
// so a value that escapes wrong is not a cosmetic bug — it is a syntax error in
// the file that decides whether the desktop has any keys at all. Every value
// that reaches the output goes through one of these.

import QtQuick

QtObject {
    // A Lua double-quoted string.
    //
    // ⚠️ BACKSLASH FIRST, ALWAYS. Escaping the quote before the backslash turns
    // one backslash into two and then escapes the second one, which is how a
    // path ending in a separator becomes an unterminated string.
    function str(value) {
        return '"' + String(value)
            .replace(/\\/g, "\\\\")
            .replace(/"/g, '\\"')
            .replace(/\n/g, "\\n")
            .replace(/\r/g, "\\r")
            + '"'
    }

    // A number, never a string, and never NaN.
    //
    // JsonAdapter hands back whatever was in the file, so a setting a person
    // typed as "12" arrives as text. Writing that straight out gives Lua a
    // string where Hyprland wants a number, and the config is refused.
    function num(value, fallback) {
        var n = Number(value)
        if (!isFinite(n))
            return String(fallback === undefined ? 0 : fallback)
        // Integers without a trailing ".0" — cosmetic, but it makes the
        // generated file diffable against a hand-written one.
        return Number.isInteger(n) ? String(n) : String(n)
    }

    function bool(value) {
        return value === true ? "true" : "false"
    }

    // The banner every generated file carries.
    //
    // It names the writer and the source, because the first question anyone has
    // about a file they did not write is "what put this here".
    function header(what) {
        return "-- " + what + "\n"
             + "--\n"
             + "-- Generated by the buchhwin shell from ~/.config/buchhwin/shell.json.\n"
             + "-- Do not edit: this file is rewritten whenever a setting changes.\n"
             + "-- Change the setting instead, or put your own lines in overrides.lua,\n"
             + "-- which loads after this file and therefore wins.\n"
             + "\n"
    }

    // A `key = value,` line inside a table literal.
    function field(indent, key, value) {
        return indent + key + " = " + value + ",\n"
    }
}
